name: Codeforces Java Solution Check

on:
  push:
    paths:
      - 'java/*.java'
      - 'testcases/*'
  pull_request:
    paths:
      - 'java/*.java'
      - 'testcases/*'

jobs:
  build-and-test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile and test all Java files
        run: |
          shopt -s nullglob
          for file in java/*.java; do
            base=$(basename "$file" .java)
            echo "Compiling $file..."
            javac "$file" || { echo "❌ Failed to compile $file"; exit 1; }
            echo "✅ Compiled $file successfully"
            
            if [ -f "testcases/$base.in" ]; then
              echo "Running $file with input testcases/$base.in..."
              java -cp java Main < "testcases/$base.in" > "/tmp/$base.actual"
              
              if [ -f "testcases/$base.out" ]; then
                echo "Comparing output with expected result..."
                # Normalize both outputs by trimming whitespace
                tr -d '\r' < "/tmp/$base.actual" | sed 's/[[:space:]]*$//' > "/tmp/$base.actual_clean"
                tr -d '\r' < "testcases/$base.out" | sed 's/[[:space:]]*$//' > "/tmp/$base.expected_clean"
                
                if diff -w "/tmp/$base.expected_clean" "/tmp/$base.actual_clean" > /dev/null; then
                  echo "✅ Output matches for $file"
                else
                  echo "❌ Output mismatch for $file"
                  echo "Expected (hex):"
                  hexdump -C "/tmp/$base.expected_clean"
                  echo "Actual (hex):"
                  hexdump -C "/tmp/$base.actual_clean"
                  echo "Expected (text):"
                  cat "/tmp/$base.expected_clean"
                  echo "Actual (text):"
                  cat "/tmp/$base.actual_clean"
                  exit 1
                fi
              else
                echo "⚠️ No expected output file found for $file, skipping output check"
              fi
            else
              echo "⚠️ No input file found for $file, skipping test"
            fi
          done
          echo "🎉 All Java files compiled and tested successfully!"
